### ISSUE TITLE
l1orderbook subscription does not handle order removal correctly: no new messages arrived on that even if best bid/ask has changed

### ISSUE THREAD

**Issue by vlddm** [idexio/idex-sdk-js#164]
l1orderbook subscription does not handle order removal correctly: no new messages arrived even if best bid/ask has changed.

It does not really related to `idex-sdk-js`, the issue is on backend, its not sending event on order removal, just havent found better place to create issue.

**Comment by bradennapier** [comment]
Apologies for the delayed response here @vlddm - I believe this issue was resolved around the time you opened the ticket though based on our logs.  Can you confirm?  

I am going to close this for now, but feel free to re-open if it is not resolved.
